/*
 * Copyright (c) 2025 Huawei Device Co., Ltd. 2025-2025. ALL rights reserved.
 */

export * from "./multiPipelineIndex";
export * from "./audioRecord";
export * from "./timeline";
export const record: () => void;
export const audioRendererInit: () => void;
export const audioRendererDestory: () => void;
export const audioRendererStart: () => void;
export const audioRendererPause: () => void;
export const audioRendererStop: () => void;
export const getRendererState: () => number;
export const registerFinishedCallback: (callBackFull: Function) => boolean;
export const unregisterFinishedCallback: () => void;
export const resetTotalWriteAudioDataSize: () => void;
export const realTimeSaveFileBuffer: () => ArrayBuffer;
export const audioEditNodeInit: (workMode: number) => number;
export const audioInAndOutInit: (NodeIds: string[], fd: number, bufferLength: number, startTime: number) => number;
export const initByPipelineCascad: (inputId: string, outputId: string, mixerId: string, audioFormat: string, buffer: ArrayBuffer) => number;
export const audioEditDestory: () => number;
export const setEqualizerMode: (equalizerMode: number, nodeId: string, inputId:string) => number;
export const setEqualizerFrequencyBandGains: (equalizerBanGains: Array<number>, nodeId: string, inputId:string, selectedNodeId?: string) => number;
export const setFormat: (channels: number, sampleRate: number, bitsPerSample: number, bitsPerSampleMode: number) => number;
export const saveFileBuffer: () => ArrayBuffer;
export const startFieldEffect: (inputId: string, mode: number, fieldEffectId: string, selectedNodeId?: string) => number;
export const resetFieldEffect: (inputId: string, mode: number, fieldEffectId: string) => number;
export const startEnvEffect: (inputId: string, envEffectId: string, mode: number, selectedNodeId?: string) => number;
export const resetEnvEffect: (inputId: string, envEffectId: string, mode: number) => number;
export const addAudioSeparation: (mode: number, uuid: string, inputId:string, selectedNodeId?: string) => number;
export const deleteAudioSeparation: (uuid: string) => number;
export const getAudioOfTap:() => ArrayBuffer;
export const addNoiseReduction: (uuid: string, inputId:string, selectedNode?: string) => number;
export const deleteNoiseReduction: (uuid: string) => number;
export const deleteSong: (inputId: string) => number;
export const startVBEffect: (inputId: string, mode: number, voiceBeautifierId: string, selectedNode?: string) => number;
export const resetVBEffect: (inputId: string, mode: number, voiceBeautifierId: string) => number;
export const deleteNode: (nodeId: string) => number;
export const registerAudioFormatCallback: (callBackFull: Function) => string[];
export const unregisterAudioFormatCallback: () => void;
export const getOptions: (nodeId: string) => string;
export const getEffectNodeList: () => Array<number>;
export const setSoundSpeedTone: (pitchSong: string, soundSpeedToneId: string, soundSpeed: number, soundTone: number, selectedNodeId?: string) => number;
export const setIsRecord: (isRecord: boolean) => void;
export const setSeparationMode: (separationMode: number) => number;
export const startGeneralVoiceChange: (inputId: string, mode: number, effectId: string, selectedNodeId?: string) => number;
export const resetGeneralVoiceChange: (inputId: string, mode: number, effectId: string) => number;
export const startPureVoiceChange: (inputId: string, effectId: string, gender: number, vocalPart: number, optionType: number, selectedNodeId?: string) => number;
export const resetPureVoiceChange: (inputId: string, effectId: string, gender: number, vocalPart: number, optionType: number) => number;
export const StartFixedPositionEffect: (x: number, y: number, z: number, spaceRenderEffectId: string, inputId: string, selectedNodeId?: string) => number;
export const StartDynamicRenderEffect: (x: number, y: number, z: number, surroundTime: number, surroundDirection: number, spaceRenderEffectId: string, inputId: string, selectedNodeId?: string) => number;
export const StartExpandEffect: (extRadius: number, extAngle: number, spaceRenderEffectId: string, inputId: string, selectedNodeId?: string) => number;
export const ResetFixedPositionEffect: (x: number, y: number, z: number, spaceRenderEffectId: string) => number;
export const ResetDynamicRenderEffect: (x: number, y: number, z: number, surroundTime: number, surroundDirection: number, spaceRenderEffectId: string) => number;
export const ResetExpandEffect: (extRadius: number, extAngle: number, spaceRenderEffectId: string) => number;
export const GetFixedPositionParams: (nodeId: string) => { x: number, y: number, z: number };
export const GetDynamicRenderParams: (nodeId: string) => { x: number, y: number, z: number, surroundTime: number, surroundDirection: number };
export const GetExpandParams: (nodeId: string) => { extRadius: number, extAngle: number };
export const registerStringCallback: (callBackFull: Function) => string;
export const unregisterStringCallback: () => void;
export const clear: () => void;
export const clearByInputId: (inputId: string, startTime: number) => void;
export const stopPipeline: () => void;
export const registerAudioCacheCallback: (callBackFull: Function) => boolean;
export const unregisterAudioCacheCallback: () => void;
export const ModifyRender: (notRenderTrackIds: string[], renderTrackIds: string[]) => void;
export const setCurrentTime: (currentTime: number) => void;
export const setEffectNodeBypass: (inputId: string, effectId: string, isBypass: boolean) => boolean;