/*
 * Copyright (c) 2025-2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package OHOS.AudioStandard;

import AudioServiceTypes;

sequenceable audio_stream_info..OHOS.AudioStandard.AudioStreamInfo;
sequenceable audio_device_descriptor..OHOS.AudioStandard.AudioDeviceDescriptor;
sequenceable audio_info..OHOS.AudioStandard.AudioProcessConfig;
interface ICoreServiceProviderIpc {
    [ipccode 0] void UpdateSessionOperation(
        [in] unsigned int sessionId,
        [in] unsigned int operation, /* SessionOperation */
        [in] unsigned int operationMsg /* SessionOperationMsg */);
    void SetDefaultOutputDevice(
        [in] int defaultOutputDevice, /* DeviceType */
        [in] unsigned int sessionID,
        [in] int streamUsage, /* StreamUsage */
        [in] boolean isRunning,
        [in] boolean skipForce);
    void GetAdapterNameBySessionId([in] unsigned int sessionID, [out] String name);
    void GetProcessDeviceInfoBySessionId(
        [in] unsigned int sessionID,
        [out] AudioDeviceDescriptor deviceInfo,
        [out] AudioStreamInfo streamInfo,
        [out] boolean isUltraFast,
        [in] boolean isReloadProcess);
    void GenerateSessionId([out] unsigned int sessionId);
    void ReloadCaptureSession(
        [in] unsigned int sessionId,
        [in] unsigned int operation /* SessionOperation */);
    void SetWakeUpAudioCapturerFromAudioServer(
        [in] AudioProcessConfig config,
        [out] int ret);
    void GetPaIndexByPortName(
        [in] String portName,
        [out] unsigned int ret);
    void SetRendererTarget(
        [in] unsigned int target,
        [in] unsigned int lastTarget,
        [in] unsigned int sessionId,
        [out] int ret);
    void StartInjection(
        [in] unsigned int target,
        [out] int ret);
    void RemoveIdForInjector([in] unsigned int sessionId);
    void ReleaseCaptureInjector();
    void RebuildCaptureInjector([in] unsigned int sessionId);
    void A2dpOffloadGetRenderPosition([out] unsigned int delayValue, [out] unsigned long sendDataSize, [out] unsigned int timeStamp, [out] int ret);
    void OnCheckActiveMusicTime([in] String reason);
    [oneway] void CaptureConcurrentCheck([in] unsigned int sessionID);
    void GetModuleNameBySessionId([in] unsigned int sessionID, [out] String name);
}
