/*
 * Copyright (c) 2025 Huawei Device Co., Ltd. 2025-2025. ALL rights reserved.
 */

/**
 * Style Constants
 */
 export class StyleConst {
    /**
     * Full width.
     */
    public static readonly FULL_WIDTH: string = '100%';
    /**
     * Ninety-five percent width.
     */
    public static readonly NINETY_FIVE_PERCENT_WIDTH: string = '95%';
    /**
     * Ninety percent width.
     */
    public static readonly NINETY_PERCENT_WIDTH: string = '90%';
    /**
     * Sixty percent width.
     */
    public static readonly SIXTY_PERCENT_WIDTH: string = '60%';
    /**
     * Fifty percent width.
     */
    public static readonly FIFTY_PERCENT_WIDTH: string = '50%';
    /**
     * Thirty percent width.
     */
    public static readonly THIRTY_PERCENT_WIDTH: string = '30%';
    /**
     * Twenty-two percent width.
     */
    public static readonly TWENTY_TWO_PERCENT_WIDTH: string = '22%';
    /**
     * Twenty percent width.
     */
    public static readonly TWENTY_PERCENT_WIDTH: string = '20%';
    /**
     * ten percent width.
     */
    public static readonly TEN_PERCENT_WIDTH: string = '10%';
    /**
     * FIVE percent width.
     */
    public static readonly FIVE_PERCENT_WIDTH: string = '5%';
    /**
     * Full height.
     */
    public static readonly FULL_HEIGHT: string = '100%';
    /**
     * One hundred and eight percent height.
     */
    public static readonly ONE_HUNDRED_AND_EIGHT_HEIGHT: string = '108%';
    /**
    * Eighty percent height.
    */
    public static readonly EIGHTY_PERCENT_HEIGHT: string = '80%';
    /**
     * Thirty percent height.
     */
    public static readonly THIRTY_PERCENT_HEIGHT: string = '30%';
    /**
     * Sixty percent height.
     */
    public static readonly SIXTY_PERCENT_HEIGHT: string = '60%';
    /**
     * Twenty five percent height.
     */
    public static readonly TWENTY_FIVE_PERCENT_HEIGHT: string = '25%';
    /**
     * nineteen percent height.
     */
    public static readonly NINETEEN_PERCENT_HEIGHT: string = '19%';
    /**
     * FIVE percent height.
     */
    public static readonly FIVE_PERCENT_HEIGHT: string = '5%';
    /**
     * Opacity.
     */
    public static readonly COMMON_OPACITY: number = 0.6;
    /**
     * Font weight.
     */
    public static readonly FONT_WEIGHT_500: number = 500;
 }